/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbConnect;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author clair
 */
public class billingf extends javax.swing.JFrame {

    /**
     * Creates new form billingf
     */
    public billingf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        add = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        tm = new javax.swing.JTextField();
        pd = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        BID = new javax.swing.JTextField();
        log = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 230, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(102, 102, 102));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 90, -1));

        add.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(102, 102, 102));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        ID.setBackground(new java.awt.Color(235, 230, 240));
        ID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(102, 102, 102));
        ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PATIENT ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 240, -1));

        tm.setBackground(new java.awt.Color(235, 230, 240));
        tm.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tm.setForeground(new java.awt.Color(102, 102, 102));
        tm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TOTAL AMOUNT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        tm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmActionPerformed(evt);
            }
        });
        jPanel1.add(tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, -1));

        pd.setBackground(new java.awt.Color(235, 230, 240));
        pd.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pd.setForeground(new java.awt.Color(102, 102, 102));
        pd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pd.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PAYMENT DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        pd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdActionPerformed(evt);
            }
        });
        jPanel1.add(pd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 240, -1));

        d.setBackground(new java.awt.Color(235, 230, 240));
        d.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        d.setForeground(new java.awt.Color(102, 102, 102));
        d.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DESCRIPTION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 240, -1));

        BID.setBackground(new java.awt.Color(235, 230, 240));
        BID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BID.setForeground(new java.awt.Color(102, 102, 102));
        BID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BID.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "BILLING ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        BID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIDActionPerformed(evt);
            }
        });
        jPanel1.add(BID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 240, -1));

        log.setBackground(new java.awt.Color(230, 189, 230));
        log.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        log.setForeground(new java.awt.Color(102, 102, 102));
        log.setText("CANCEL");
        log.setToolTipText("");
        log.setBorder(null);
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        jPanel1.add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
       ManagerDashboard md = new ManagerDashboard();
            md.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_logActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       String billingId = BID.getText(); 
    String patientId = ID.getText();
    String total = tm.getText();
    String pay = pd.getText().trim();
    String des = d.getText();

    if (billingId.isEmpty() || patientId.isEmpty() || total.isEmpty() || pay.isEmpty() || des.isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields are required.");
        return;
    }

    try {
        dbConnect dbc = new dbConnect();
        String sql = "UPDATE tbl_billing SET p_id = ?, total_amount = ?, payment_date = ?, description = ? WHERE b_id = ?";
        PreparedStatement pstmt = dbc.getConnection().prepareStatement(sql);

        pstmt.setString(1, patientId);
        pstmt.setString(2, total);
        pstmt.setString(3, pay);
        pstmt.setString(4, des);
        pstmt.setString(5, billingId);

        int rows = pstmt.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "Billing updated!");
        } else {
            JOptionPane.showMessageDialog(null, "No record updated. Check Billing ID.");
        }

        pstmt.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    
    }//GEN-LAST:event_updateActionPerformed
    }
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
     
       String patientId = ID.getText();
    String total = tm.getText();
    String pay = pd.getText().trim();
    String des = d.getText();

    if (patientId.isEmpty() || total.isEmpty() || pay.isEmpty() || des.isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields are required.");
        return;
    }

    try {
        dbConnect dbc = new dbConnect();
        String sql = "INSERT INTO tbl_billing (p_id, total_amount, payment_date, description) " +
                     "VALUES ('" + patientId + "', '" + total + "', '" + pay + "', '" + des + "')";

        if (dbc.insertData(sql)) {
            JOptionPane.showMessageDialog(null, "Billing added!");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to add billing.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_addActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void tmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmActionPerformed

    private void pdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void BIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billingf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billingf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billingf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billingf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billingf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField BID;
    public javax.swing.JTextField ID;
    public javax.swing.JButton add;
    public javax.swing.JTextField d;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton log;
    public javax.swing.JTextField pd;
    public javax.swing.JTextField tm;
    public javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
