/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author clair
 */
public class EditF extends javax.swing.JFrame {

    /**
     * Creates new form EditF
     */
    public EditF() {
        initComponents();
    }
    
    
    
    public boolean duplicateCheck() {
    dbConnect dbc = new dbConnect();
    try {
        String query = "SELECT * FROM tbl_patient WHERE p_firstname = '" + fn.getText().trim() + "' AND p_lastname = '" + ln.getText().trim() + "'";
        ResultSet resultSet = dbc.getData(query);

        if (resultSet.next()) {
            JOptionPane.showMessageDialog(null, "Patient name already exists!");
            fn.setText("");
            ln.setText("");
            return true;
        } else {
            return false;
        }

    } catch (SQLException ex) {
        System.out.println("" + ex);
        return false;
    }
}

      
         public boolean updateCheck() {
     dbConnect dbc = new dbConnect();
    try {
        String query = "SELECT * FROM tbl_patient WHERE p_firstname = '" + fn.getText().trim() + "' AND p_lastname = '" + ln.getText().trim() + "'";
        ResultSet resultSet = dbc.getData(query);

        if (resultSet.next()) {
            JOptionPane.showMessageDialog(null, "Patient name already exists!");
            fn.setText("");
            ln.setText("");
            return true;
        } else {
            return false;
        }

    } catch (SQLException ex) {
        System.out.println("" + ex);
        return false;
    }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        ADR = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        add = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        log = new javax.swing.JButton();
        gender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fn.setBackground(new java.awt.Color(235, 230, 240));
        fn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        fn.setForeground(new java.awt.Color(102, 102, 102));
        fn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "FIRSTNAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 40));

        ln.setBackground(new java.awt.Color(235, 230, 240));
        ln.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ln.setForeground(new java.awt.Color(102, 102, 102));
        ln.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ln.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "LASTNAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        jPanel1.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 40));

        age.setBackground(new java.awt.Color(235, 230, 240));
        age.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        age.setForeground(new java.awt.Color(102, 102, 102));
        age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        age.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "AGE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, 40));

        dob.setBackground(new java.awt.Color(235, 230, 240));
        dob.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dob.setForeground(new java.awt.Color(102, 102, 102));
        dob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dob.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DATE OF BIRTH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, 40));

        ADR.setBackground(new java.awt.Color(235, 230, 240));
        ADR.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ADR.setForeground(new java.awt.Color(102, 102, 102));
        ADR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ADR.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ADDRESS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.add(ADR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 220, 40));

        cn.setBackground(new java.awt.Color(235, 230, 240));
        cn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cn.setForeground(new java.awt.Color(102, 102, 102));
        cn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cn.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CONTACT NUMBER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 220, 40));

        update.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(102, 102, 102));
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 90, -1));

        add.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(102, 102, 102));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        ID.setBackground(new java.awt.Color(235, 230, 240));
        ID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(102, 102, 102));
        ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 40));

        log.setBackground(new java.awt.Color(230, 189, 230));
        log.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        log.setForeground(new java.awt.Color(102, 102, 102));
        log.setText("CANCEL");
        log.setToolTipText("");
        log.setBorder(null);
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        jPanel1.add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 90, 30));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHERS" }));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
    PatientF pf = new PatientF();
     pf.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_logActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
 if (fn.getText().isEmpty() || ln.getText().isEmpty() || age.getText().isEmpty() || gender.getSelectedItem().equals(ID) ||
    dob.getText().isEmpty() || ADR.getText().isEmpty() || cn.getText().isEmpty()) {

    JOptionPane.showMessageDialog(null, "All fields are required");

} else {

    dbConnect dbc = new dbConnect();
   dbc.updateData("UPDATE tbl_patient SET " +
    "p_firstname = '" + fn.getText() + "', " +
    "p_lastname = '" + ln.getText() + "', " +
    "p_age = '" + age.getText() + "', " +
    "p_gender'" + gender.getSelectedItem() + "', " +
    "p_dob = '" + dob.getText() + "', " +
    "p_address = '" + ADR.getText() + "', " +
    "p_contactNumber = '" + cn.getText() + "' " +
    "WHERE p_id = '" + ID.getText() + "'");
   JOptionPane.showMessageDialog(null,"Updated Successfully!");
 {


        PatientF pf = new PatientF();
        pf.setVisible(true);
        this.dispose();
 
        }        }    }//GEN-LAST:event_updateActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
   if (fn.getText().isEmpty() || ln.getText().isEmpty() || age.getText().isEmpty() ||gender.getSelectedItem().equals(ID)||
            dob.getText().isEmpty() || ADR.getText().isEmpty() || cn.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "All fields are required");

        } else {

            dbConnect dbc = new dbConnect();

        
            String sql = "INSERT INTO tbl_patient(p_firstname, p_lastname, p_age,p_gender , p_dob, p_address, p_contactNumber) " +
           "VALUES ('" + fn.getText() + "','" + ln.getText() + "','" + age.getText() + "','" +
             dob.getText() + "','" + ADR.getText() + "','" + cn.getText() + "','" + 
             gender.getSelectedItem().toString() + "')";


            if (dbc.insertData(sql)) {
                JOptionPane.showMessageDialog(null, "Patient added successfully!");
                PatientF p = new PatientF();
                p.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Connection Error");
            }
      }
            }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ADR;
    public javax.swing.JTextField ID;
    public javax.swing.JButton add;
    public javax.swing.JTextField age;
    public javax.swing.JTextField cn;
    public javax.swing.JTextField dob;
    public javax.swing.JTextField fn;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField ln;
    private javax.swing.JButton log;
    public javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
